desc: "Xen-Troops development setup for Renesas RCAR Gen4 hardware"
min_ver: "0.15"

variables:
  YOCTOS_WORK_DIR: "yocto"
  DOM0_BUILD_DIR: "build-dom0"
  DOMD_BUILD_DIR: "build-domd"
  DOMU_BUILD_DIR: "build-domu"
  XT_DOMD_DTB_NAME: "%{SOC_FAMILY}-%{MACHINE}-domd.dtb"
  XT_DOMU_DTB_NAME: "%{SOC_FAMILY}-%{MACHINE}-domu.dtb"
  XT_XEN_DTB_NAME: "%{SOC_FAMILY}-%{MACHINE}-xen.dtb"
  XT_GENERIC_DOMU_TAG: ""
  XT_DOMD_CONFIG_NAME: "domd-%{MACHINE}.cfg"
  XT_DOMU_CONFIG_NAME: "domu-%{MACHINE}.cfg"
  # Android related
  ANDROID_KERNEL_DIR: "android_kernel"
  DOMA_DIR: "android"
  XT_DOMA_TAG: ""
  XT_DOMA_DTB_NAME: ""
  XT_DOMA_KERNEL_EXTRA_MODULES: ""
  XT_DOMA_SOURCE_GROUP: ""
  XT_DOMA_CONFIG_NAME: "doma-virtio.cfg"
  ANDROID_KERNEL_BUILD_CONFIG: "//common-modules/xen-virtual-device:xen_virtual_device_aarch64_dist"
  ANDROID_KERNEL_DEPLOY_DIR: "out/deploy/common-modules/xen-virtual-device/xen_virtual_device_aarch64"
  ANDROID_DEVICE: "xenvm_trout_arm64"
  ANDROID_LUNCH_TARGET: "aosp_xenvm_trout_arm64-trunk_staging-userdebug"
  AGL_GUEST_MACHINE: "virtio-aarch64"
  AGL_GUEST_IMAGE_IVI: "agl-ivi-demo-flutter-guest"
  AGL_GUEST_IMAGE_IC: "agl-cluster-demo-flutter-guest"
  #AGL_GUEST_IMAGE_IC: "agl-instrument-cluster-standalone-demo"
  XT_DOMAGL_IVI_TAG: ""
  XT_DOMAGL_IC_TAG: ""
  XT_AUTOSTART_DOMA: "disable"
  XT_AUTOSTART_DOMU: "disable"
  XT_AUTOSTART_DOMAGL_IVI: "enable"
  XT_AUTOSTART_DOMAGL_IC: "enable"

common_data:
  # Sources used by all yocto-based domains
  sources: &COMMON_SOURCES
    - type: git
      url: "git://git.yoctoproject.org/poky"
      rev: scarthgap
    - type: git
      url: "git://git.openembedded.org/meta-openembedded"
      rev: scarthgap
    - type: git
      url: "git://git.yoctoproject.org/meta-virtualization"
      rev: scarthgap
    - type: git
      url: "https://github.com/xen-troops/meta-xt-common.git"
      rev: master

  # Common configuration options for all yocto-based domains
  conf: &COMMON_CONF
    - [DL_DIR, "${TOPDIR}/../common_data/downloads"]
    - [SSTATE_DIR, "${TOPDIR}/../common_data/sstate"]

    # Skip warning about missing "virtualization" distro feature
    - [SKIP_META_VIRT_SANITY_CHECK, "1"]

    # Use hypervisor console on all guests
    - [SERIAL_CONSOLES, "115200;hvc0"]

    # Remove features that we are not using
    - [DISTRO_FEATURES:remove, "x11 gtk gobject-introspection-data wifi nfc
            bluetooth irda zeroconf 3g sysvinit acl alsa argp pcmcia usbgadget
            usbhost  ptest multiarch  vulkan sysvinit pulseaudio"]

    - [PREFERRED_VERSION_xen-tools, "4.19.0+git%"]
    - [PREFERRED_VERSION_xen, "4.19.0+git%"]

    # Specify the linux kernel version
    - [PREFERRED_VERSION_linux-renesas, "6.12%"]
    - [LINUXLIBCVERSION, "6.12%"]

components:
  dom0:
    build-dir: "%{YOCTOS_WORK_DIR}"
    default: true
    sources:
      - *COMMON_SOURCES
      - type: git
        url: git://git.yoctoproject.org/meta-selinux
        rev: scarthgap
    builder:
      type: yocto
      work_dir: "%{DOM0_BUILD_DIR}"
      conf:
        - [BBMULTICONFIG, "dom0 domd"]
        - *COMMON_CONF
        - [MACHINE, "sparrow-hawk"]
        - [XT_DOMD_CONFIG_NAME, "%{XT_DOMD_CONFIG_NAME}"]
        - [XT_DOMD_DTB_NAME, "%{XT_DOMD_DTB_NAME}"]
        - [XT_DEVICE_TREES, "%{XT_DOMD_DTB_NAME}"]

        - [MACHINE_EXTRA_RRECOMMENDS:remove, "linux-fitimage"]

        - [DISTRO_FEATURES:append, " usrmerge systemd"]
        - [VIRTUAL-RUNTIME_init_manager, "systemd"]



      layers:
        - "../meta-virtualization"
        - "../meta-selinux"
        - "../meta-openembedded/meta-oe"
        - "../meta-openembedded/meta-filesystems"
        - "../meta-openembedded/meta-python"
        - "../meta-openembedded/meta-networking"
        - "../meta-xt-common/meta-xt-control-domain"
        - "../meta-xt-common/meta-xt-dom0"
        - "../meta-xt-common/meta-xt-domx"
        - "../meta-xt-common/meta-xt-driver-domain"
        - "../meta-xt-common/meta-xt-security"
      build_target: mc:dom0:xen-full-image
      target_images:
        - "tmp-dom0/deploy/images/%{MACHINE}/fitImage"
        - "tmp-domd/deploy/images/%{MACHINE}/flash.bin"
        - "tmp-domd/deploy/images/%{MACHINE}/core-image-weston-%{MACHINE}.rootfs.ext4"
images:
  full:
    type: gpt
    desc: "Full SD-card/eMMC image"
    partitions:
      boot:
        gpt_type: 21686148-6449-6E6F-744E-656564454649 # BIOS boot partition (kinda...)
        type: ext4
        size: 256 MiB
      domd_rootfs:
        gpt_type: B921B045-1DF0-41C3-AF44-4C6F280D3FAE # Linux aarch64 root
        type: raw_image
        image_path: "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp-domd/deploy/images/%{MACHINE}/core-image-weston-%{MACHINE}.rootfs.ext4"

parameters:
  MACHINE:
    desc: "RCAR Gen4-based device"
    "sparrow-hawk":
      default: true
      overrides:
        variables:
          MACHINE: "sparrow-hawk"
          SOC_FAMILY: "r8a779g3"
        components:
          dom0:
            sources:
              - type: git
                url: https://github.com/rcar-community/meta-sparrow-hawk
                rev: v2026-01-30
            builder:
              layers:
                - "../meta-sparrow-hawk"
  ADD_META_TEST:
    desc: "Add meta-test layer and some configs"
    "no":
      desc: "Nothing to do"
      default: true
    "yes":
      overrides:
        components:
          dom0:
            builder:
              layers:
                - "../../../meta-xen-dom0"
                - "../../../meta-xen-domd"
                - "../../../meta-xen-domx"
                - "../meta-openembedded/meta-multimedia"
              conf:
                - [XT_XEN_DTB_NAME, "%{XT_XEN_DTB_NAME}"]
                - [XT_DEVICE_TREES:append:mc:domd, " %{XT_XEN_DTB_NAME}"]
        images:
          full:
            partitions:
              boot:
                items:
                  "flash.bin": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp-domd/deploy/images/%{MACHINE}/flash.bin"
                  "fitImage": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp-dom0/deploy/images/%{MACHINE}/fitImage"
                  "/boot/fitImage": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp-dom0/deploy/images/%{MACHINE}/fitImage"

  USE_GRAPHICS_PACKAGE:
    desc: "Enable GPU on DomD"
    "no":
      desc: "Nothing to do"
      overrides:
        components:
          dom0:
            builder:
              conf:
                - [XT_DOMD_USE_CPU_GRAPHICS, "1"]
    "yes":
      default: true
      overrides:
        components:
          dom0:
            builder:
              conf:
                # Enable Gfx Pkgs
                - [MACHINE_FEATURES:append, " gsx"]
                - [XT_DOMD_USE_CPU_GRAPHICS, "0"]
              layers:
                - "../../../meta-xen-domd-gfx"

  ENABLE_ZEPHYR:
    desc: "Build zephyr images and put into fitImage"
    "no":
      default: true
    "yes":
      overrides:
        components:
          dom0:
            sources:
              - type: git
                url: https://github.com/soburi/meta-zephyr.git
                rev: sodev
            builder:
              layers:
                - "../meta-zephyr/meta-zephyr-core"
                - "../../../meta-xen-domz"
              conf:
                - [ZEPHYR_TOOLCHAIN_VARIANT, "zephyr"]
                - [ZEPHYR_SDK_EXTERNAL, "0"]
                - [XT_GUEST_INSTALL:append, " domz"]
