TMPDIR = "${TOPDIR}/tmp-dom0"
MACHINE = "${DOM0_MACHINE}"
XT_DOM_NAME = "dom0"
XT_GUEST_INSTALL = "domd"
XT_DOMD_CONFIG_NAME ?= "domd-${DOMD_MACHINE}.cfg"
XT_DEVICE_TREES ?= "${XT_DOMD_DTB_NAME}"
XT_DOMU_CONFIG_NAME ?= "domu-${MACHINE}.cfg"
XT_AUTOSTART_DOMA ?= "disable"
XT_AUTOSTART_DOMU ?= "disable"
XT_AUTOSTART_DOMAGL_IVI ?= "enable"
XT_AUTOSTART_DOMAGL_IC ?= "enable"
EXTERNALSRC:pn-core-image-thin-initramfs ?= "${TOPDIR}/tmp-domd/deploy/images/${DOMD_MACHINE}"
BAD_RECOMMENDATIONS:append = " udev-hwdb"
DISTRO_FEATURES:append = " usrmerge systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
RRECOMMENDS:${KERNEL_PACKAGE_NAME}-base = ""
MACHINE_EXTRA_RRECOMMENDS:remove = "linux-fitimage"

do_image_complete:pn-core-image-thin-initramfs[mcdepends] += " \
    mc:dom0:domd:virtual/kernel:do_deploy \
    mc:dom0:domd:xen:do_deploy \
    mc:dom0:domd:xen-tools:do_deploy \
    mc:dom0:domd:arm-trusted-firmware:do_deploy \
"
