TMPDIR = "${TOPDIR}/tmp-dom0"
DOM0_MACHINE ?= "generic-armv8-xt"
MACHINE = "${DOM0_MACHINE}"
XT_DOM_NAME = "dom0"
XT_GUEST_INSTALL = "domd"
XT_DOMU_CONFIG_NAME ?= "domu-${MACHINE}.cfg"
XT_AUTOSTART_DOMA ?= "disable"
XT_AUTOSTART_DOMU ?= "disable"
XT_AUTOSTART_DOMAGL_IVI ?= "enable"
XT_AUTOSTART_DOMAGL_IC ?= "enable"
BAD_RECOMMENDATIONS:append = " udev-hwdb"
DISTRO_FEATURES:append = " usrmerge systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
RRECOMMENDS:${KERNEL_PACKAGE_NAME}-base = ""
