TMPDIR = "${TOPDIR}/tmp-dom0"
XT_DOM_NAME = "dom0"
XT_GUEST_INSTALL = "domd"
BAD_RECOMMENDATIONS:append = " udev-hwdb"
DISTRO_FEATURES:append = " usrmerge systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
RRECOMMENDS:${KERNEL_PACKAGE_NAME}-base = ""
