TMPDIR = "${TOPDIR}/tmp-domd"
XT_DOM_NAME = "domd"
XT_DEVICE_TREES = "${XT_DOMD_DTB_NAME} ${XT_XEN_DTB_NAME}"
XT_GUEST_INSTALL = ""
INIT_MANAGER = "systemd"
DISTRO_FEATURES:append = " usrmerge systemd pam wayland"
DISTRO_FEATURES_NATIVESDK:append = " wayland"
DISTRO_FEATURES:remove:xen-tools = "systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
SDKIMAGE_FEATURES:append = " staticdev-pkgs"
LICENSE_FLAGS_ACCEPTED = "commercial"
MACHINE_FEATURES:append = " cas"
IMAGE_FSTYPES:append = " ext4"
PACKAGECONFIG:remove = "perf tools-profile"
RENESAS_EXTRA_IMAGE_FEATURES:remove = "tools-profile"
CORE_IMAGE_EXTRA_INSTALL:remove = "perf"
IMAGE_INSTALL:append = " socat iperf3 smcroute snort iperf3 htop tcpdump coreutils ethtool"
MACHINE_EXTRA_RRECOMMENDS:remove = "linux-fitimage"
BB_MULTI_PROVIDER_ALLOWED:append = "virtual/libgl virtual/libgles1 virtual/libgles2"
PREFERRED_PROVIDER_virtual/libgles1 = ""
PREFERRED_PROVIDER_virtual/libgles2 = "user-module-gles"
PREFERRED_PROVIDER_virtual/egl = "libegl"
PREFERRED_PROVIDER_virtual/libgl = ""
PREFERRED_PROVIDER_virtual/mesa = ""
PREFERRED_PROVIDER_virtual/libgbm = "libgbm"
PREFERRED_PROVIDER_libgbm-dev = "libgbm"

IMAGE_INSTALL:append = "${@oe.utils.conditional('XT_DOMD_USE_CPU_GRAPHICS', '1', ' mesa', '', d)}"
DISTRO_FEATURES:remove = "${@oe.utils.conditional('XT_DOMD_USE_CPU_GRAPHICS', '1', ' ptest x11 vulkan', '', d)}"
DISTRO_FEATURES_NATIVESDK:append = "${@oe.utils.conditional('XT_DOMD_USE_CPU_GRAPHICS', '1', ' x11', '', d)}"
BBMASK:append = "${@oe.utils.conditional('XT_DOMD_USE_CPU_GRAPHICS', '1', '|kernel-module-gles|user-module-gles|meta-sparrow-hawk/recipes-graphics/wayland/wayland-wsegl|meta-sparrow-hawk/recipes-graphics/wayland/wayland-kms|meta-sparrow-hawk/recipes-graphics/wayland/libgbm|meta-sparrow-hawk/recipes-graphics/wayland/weston_%.bbappend|meta-sparrow-hawk/recipes-graphics/packagegroups/packagegroup-renesas-graphics.bb', '', d)}"
