# =====================================================================
# Zephyr VirtIO block frontend guest configuration
# =====================================================================

seclabel='system_u:system_r:domD_t'

# Guest name
name = "zephyr_virtio_blk"

# Kernel image to boot
kernel = "/usr/lib/xen/boot/zephyr_virtio_blk.bin"

# Initial memory allocation (MB)
memory = 16

# Number of VCPUS
vcpus = 1

gic_version = "v3"

on_crash = 'preserve'

virtio = [
    "type=virtio,device2,transport=mmio,backend=zephyr_vhost_blk,backend_type=standalone,grant_usage=1"
]
