# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "xen-zephyr"
BBFILE_PATTERN_xen-zephyr := "^${LAYERDIR}/"
BBFILE_PRIORITY_xen-zephyr = "19"

LAYERSERIES_COMPAT_xen-zephyr = "scarthgap"
